# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 01:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0039_collectionviewrestriction'),
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('question', models.CharField(max_length=510)),
                ('answers', wagtail.wagtailcore.fields.StreamField((('answer', wagtail.wagtailcore.blocks.CharBlock(max_length=510, required=True)), ('suggestion', wagtail.wagtailcore.blocks.RichTextBlock(required=True))))),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
